name: Test pre-commit composite action

on:
  push:
    branches:
      - "main"
    paths:
      - "actions/pre-commit/**"
      - ".github/workflows/test-pre-commit.yaml"
  pull_request:
    paths:
      - "actions/pre-commit/**"
      - ".github/workflows/test-pre-commit.yaml"

jobs:
  pre-commit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Use pre-commit composite action
        uses: ./actions/pre-commit
