name: Test GHCR Login composite action

on:
  push:
    branches:
      - "main"
    paths:
      - "actions/ghcr-login/**"
      - ".github/workflows/test-ghcr-login.yaml"
  pull_request:
    paths:
      - "actions/ghcr-login/**"
      - ".github/workflows/test-ghcr-login.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Use GHCR Login composite action
        uses: ./actions/ghcr-login
